version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15432:5432"
    volumes:
      - my-datavolume:/var/lib/postgres 
    networks:
      - postgres-network
      
networks: 
  postgres-network:
    driver: bridge

volumes:
  my-datavolume: